[package]
name = "deft-video"
version = "0.1.0"
edition = "2021"

license = "GPL-2.0-or-later"
description = "Video component for deft"
authors = ["KasonYang <me@kason.fun>"]

[dependencies]
deft = "0.10.0"
ffmpeg-next = "7.1.0"
skia-safe = { package = "deft-skia-safe", version = "*" }
serde = { version = "1.0.213", features = ["derive"] }
cpal = "0.15.3"
ringbuf = "0.3.3"
bytemuck = "1.13.1"
anyhow = "1.0.93"
num_cpus = "1.16.0"
deft-macros = "0.3.0"
libc = "0.2.172"
